## ```Imports```
---

In [11]:
# standard libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# modeling libraries
from classifiers_copy1 import classify

# preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## ```Initial Modeling```
---

In [2]:
fraud = pd.read_csv('../SmallBalancedClasses.csv')

In [3]:
fraud.head(3)

,trans_date_trans_time,cc_num,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,hour
0,2019-12-13 05:41:26,378278619832195,fraud_Dach-Nader,misc_net,3.17,F,Eugene,OR,97403,44.0385,-123.0614,191096,"Scientist, physiological",1964-04-06,44.716305,-123.984986,0,6
1,2020-03-11 22:31:29,4725837176265195730,fraud_Torphy-Goyette,shopping_pos,16.37,F,Jay,FL,32565,30.8985,-87.1332,5719,Higher education careers adviser,1994-11-05,30.635023,-88.086411,0,23
2,2019-11-12 01:08:37,373905417449658,fraud_Bruen-Yost,misc_pos,8.54,F,Meridian,TX,76665,31.9290,-97.6443,2526,Phytotherapist,1970-11-12,32.399693,-97.414423,0,2

In [4]:
fraud.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'gender', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job',
       'dob', 'merch_lat', 'merch_long', 'is_fraud', 'hour'],
      dtype='object')

In [5]:
# dummy for object variables
df_fraud = fraud.copy()
df_fraud = pd.get_dummies(fraud, columns=['gender','city','state','category','merchant'])
df_fraud.shape

(15012, 1662)

In [13]:
# setting up X/y
X = df_fraud.drop(columns=['trans_date_trans_time','lat', 'long','job','merch_lat', 'merch_long','dob'])
y = df_fraud['is_fraud']

# train/test split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42,stratify=y)

# standard scale the data
ss = StandardScaler()
X_train_ss = ss.fit_transform(X_train)
X_test_ss = ss.transform(X_test)

In [15]:
result = classify(X_train_ss,X_test_ss,y_train,y_test)

In [16]:
result

,Train Acc,Test Acc,Acc-diff,Train-F1,Test-F1,F1-diff,Train-Pres,Test-Pres,Pres-diff,Train_Recall,Test-Recall,Recall_diff
knn,0.769962,0.673062,0.096900,0.789431,0.701823,0.087608,0.727886,0.644931,0.082955,0.862345,0.769723,0.092622
logreg,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
dt,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
bag,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
bag_knn,0.780709,0.676792,0.103917,0.797871,0.703350,0.094521,0.740015,0.649797,0.090219,0.865542,0.766525,0.099017
bag_log,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
rf,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
et,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
ada,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
gboost,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
svc,0.999911,0.980016,0.019895,0.999911,0.979735,0.020176,0.999822,0.993425,0.006398,1.000000,0.966418,0.033582